site_name: Plant Genomics Training
site_description: Training for plant genomics
site_author: Anna Syme
#site_favicon: favicon.ico

site_url: 'https://plant-genomics.github.io/training/'

#repo_name: 'plant-genomics/training'
#repo_url: 'https://github.com/plant-genomics/training'

google_analytics: ['UA-154956469-2', 'auto']

copyright: '<br><br><br><br><br><br><br>&copy; The authors; 2020-'

#theme: yeti
#theme: cluster
theme: 
  name: windmill
  font: Roboto


nav:
  - Home: index.md
  - Tutorials: modules/tutorials.md
  - Galaxy: modules/galaxy.md
#  - Genome assembly: modules/chloroplast_assembly.md
  - Phylogenomics: modules/phylogenomics.md
#  - Variant calling: modules/variants.md
#  - RNA-seq: modules/rna.md
  - Data: modules/data.md
  - Databases: modules/databases.md
  - Tools: modules/tools.md
  - Papers: modules/papers.md
  - Help: modules/help.md


extra:
    article_nav_top: false
    article_nav_bottom: false
    logo: leaf2.svg
    feature:
        tabs: true
    social:
        type: 'github'
        link: 'https://github.com/plant-genomics/training'
        fa_logo: 'pagelines'


markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite
    - pymdownx.details
    - footnotes

extra_css:
    - css/style.css






# - About: about/index.md
